### ISSUE TITLE
Security contact

### ISSUE THREAD

**Issue by mal-tee** [JosephTribbianni/Stitch#4]
Hello maintainer(s), 

I am a security researcher from the Institute of Application Security at TU Braunschweig, Germany. We discovered a (potential) security vulnerability in your project.

We would like to report this vulnerability to you in a responsible and ethical manner.
Therefore, we do not want to disclose any details of the vulnerability publicly until you have had a chance to review and fix it.

**Could you please let us know your prefered way of receiving security reports?**

You can contact us at ias-disclosure@tu-braunschweig.de or by replying to this issue.

Thank you for your attention and cooperation.

**Comment by mal-tee** [comment]
Dear maintainer(s),

I am getting in touch again to ask you for a security contact. We want to disclose a (potential) security vulnerability in your project responsibly. Feel free to respond with your preferred method of disclosure in this issue or via email: ias-disclosure@tu-braunschweig.de 

Please note that we anticipate to release our findings later this year.

Thank You

**Comment by Ca1337** [comment]
> Dear maintainer(s),
> 
> I am getting in touch again to ask you for a security contact. We want to disclose a (potential) security vulnerability in your project responsibly. Feel free to respond with your preferred method of disclosure in this issue or via email: [ias-disclosure@tu-braunschweig.de](mailto:ias-disclosure@tu-braunschweig.de)
> 
> Please note that we anticipate to release our findings later this year.
> 
> Thank You

**This repository is a fully functional PHP backdoor (web-shell), not a web application.  I hope I won’t see jokes about “finding security vulnerabilities in web-shells” in academic publications this year.**
-------------------------------
这个仓库是一个功能齐全的php后门（Web-shell），而非web应用，我希望我今年不会在学术出版物中看到“在web-shell”中发现安全性漏洞的笑话。

**Comment by Morpheu5** [comment]
Shut up @Ca1337, you are lucky these issues aren't being troll-flooded.
